from .base_llm import BaseLLM
from .data import Dataset
from .sft import TokenizedDataset, test_model


def load() -> BaseLLM:
    from pathlib import Path

    from peft import PeftModel

    model_name = "rft_model"
    model_path = Path(__file__).parent / model_name

    llm = BaseLLM()
    llm.model = PeftModel.from_pretrained(llm.model, model_path).to(llm.device)
    llm.model.eval()

    return llm


def format_example(question: str, answer: float, reasoning: str) -> dict[str, str]:
    """
    Unlike sft.format_example, the target here is the full reasoning trace (which
    already ends in <answer>...</answer>), not just a bare answer tag - this is what
    teaches the model to "think" before answering.
    """
    return {
        "question": question,
        "answer": reasoning,
    }


def train_model(
    output_dir: str,
    **kwargs,
):
    # Reuse much of the SFT code here
    from peft import LoraConfig, get_peft_model
    from transformers import Trainer, TrainingArguments

    llm = BaseLLM()

    # Reasoning traces are longer and more varied than SFT's bare answers, so this
    # adapter may need a bit more capacity - bump the rank slightly while staying
    # well under the 50MB submission cap.
    lora_config = LoraConfig(
        r=16,
        lora_alpha=64,
        target_modules="all-linear",
        bias="none",
        task_type="CAUSAL_LM",
    )
    llm.model = get_peft_model(llm.model, lora_config)
    llm.model.enable_input_require_grads()

    # Load the rejection-sampled (question, answer, reasoning) triples generated by
    # datagen.py's generate_dataset (data/rft.json). data.Dataset is generic enough
    # to load this directly - it just json-loads DATA_DIR/{split}.json regardless
    # of how many elements are in each entry.
    train_data = Dataset("rft")
    tokenized_dataset = TokenizedDataset(llm.tokenizer, train_data, format_example)

    training_args = TrainingArguments(
        output_dir=output_dir,
        logging_dir=output_dir,
        report_to="tensorboard",
        gradient_checkpointing=True,
        learning_rate=2e-4,
        num_train_epochs=5,
        per_device_train_batch_size=32,
        save_strategy="no",  # avoid bulky intermediate checkpoint-N/ folders
    )

    trainer = Trainer(
        model=llm.model,
        args=training_args,
        train_dataset=tokenized_dataset,
    )
    trainer.train()

    # Save just the LoRA adapter (small) rather than the full base model.
    trainer.save_model(output_dir)
    test_model(output_dir)


if __name__ == "__main__":
    from fire import Fire

    Fire({"train": train_model, "test": test_model, "load": load})